use crate::core::config::ProjectConfig;
use crate::core::env_file::EnvFile;
use crate::core::project::Project;
use crate::core::schema::{Schema, VarType};
use crate::errors::{GraxaimError, Result};
use crate::ui;

/// `graxaim schema init` — infer schema from active profile
pub fn execute_init() -> Result<()> {
    let project = Project::find()?;
    let config = ProjectConfig::load(&project)?;
    let active = config
        .active_profile()
        .ok_or(GraxaimError::NoActiveProfile)?;

    let env_path = project.root.join(format!(".env.{}", active));
    let env = EnvFile::from_path(&env_path)?;
    let schema = Schema::infer_schema(&env);

    let schema_path = project.root.join(".graxaim/schema.toml");
    let content = schema.to_toml_string();
    std::fs::write(&schema_path, &content).map_err(GraxaimError::Io)?;

    ui::output::success(&format!(
        "Schema generated from '{}' profile with {} variables",
        active,
        schema.vars.len()
    ));
    println!("  Written to {}", schema_path.display());
    println!("  Review and adjust types, constraints, and descriptions.");

    Ok(())
}

/// `graxaim schema generate-example` — generate .env.example from schema
pub fn execute_generate_example() -> Result<()> {
    let project = Project::find()?;
    let schema_path = project.root.join(".graxaim/schema.toml");

    if !schema_path.exists() {
        return Err(GraxaimError::Custom(
            "No schema found. Run 'graxaim schema init' to create one.".to_string(),
        ));
    }

    let schema = Schema::load(&schema_path)?;
    let example_path = project.root.join(".env.example");

    let mut lines = Vec::new();
    lines.push("# .env.example — generated by graxaim schema generate-example".to_string());
    lines.push("# Copy this file to .env.<profile> and fill in the values.".to_string());
    lines.push(String::new());

    // Sort keys for deterministic output
    let mut keys: Vec<&String> = schema.vars.keys().collect();
    keys.sort();

    for key in keys {
        let var = &schema.vars[key];

        // Description comment
        if let Some(desc) = &var.description {
            lines.push(format!("# {}", desc));
        }

        // Type and required info
        let type_name = var.var_type.to_string();
        let required_str = if var.required { "required" } else { "optional" };
        lines.push(format!("# Type: {} ({})", type_name, required_str));

        // Enum values hint
        if let VarType::Enum { values } = &var.var_type {
            lines.push(format!("# Allowed values: {}", values.join(", ")));
        }

        // URL scheme hint
        if let VarType::Url {
            schemes: Some(schemes),
        } = &var.var_type
        {
            lines.push(format!("# Allowed schemes: {}", schemes.join(", ")));
        }

        // Determine the example value
        let example_value = if let Some(ex) = &var.example {
            ex.clone()
        } else if let Some(def) = &var.default {
            def.clone()
        } else {
            // Generate a placeholder based on type
            match &var.var_type {
                VarType::String { .. } => String::new(),
                VarType::Integer { .. } => String::new(),
                VarType::Port => "3000".to_string(),
                VarType::Boolean => "false".to_string(),
                VarType::Url { schemes } => {
                    let scheme = schemes
                        .as_ref()
                        .and_then(|s| s.first().cloned())
                        .unwrap_or_else(|| "https".to_string());
                    format!("{}://", scheme)
                }
                VarType::Email => String::new(),
                VarType::Enum { values } => values.first().cloned().unwrap_or_default(),
                VarType::Path { .. } => String::new(),
            }
        };

        lines.push(format!("{}={}", key, example_value));
        lines.push(String::new());
    }

    let content = lines.join("\n") + "\n";
    std::fs::write(&example_path, &content).map_err(GraxaimError::Io)?;

    ui::output::success(&format!(
        "Generated .env.example with {} variables",
        schema.vars.len()
    ));
    println!("  Written to {}", example_path.display());

    Ok(())
}
